### ISSUE TITLE
Node Label Command Causes Annotald to Freeze

### ISSUE THREAD

**Issue by diertani** [Annotald/annotald#81]
Using L in order to change the label of a pos-tag node manually now causes Annotald to freeze completely.  Error message:

Uncaught TypeError: isLeafNode is not a function

This is different from the other freezing issue, because it wasn't the cause with the previous versions of annotald prior to 1.3.5/6.  

I'm not experiencing this problem with phrasal nodes, only with pos-tags.

**Comment by aecay** [comment]
This should be fixed in 1.3.7, now on babel.

**Comment by diertani** [comment]
Yes!  It's fine now.  Thank you!

On Wed, Oct 14, 2015 at 8:29 AM, Aaron Ecay <notifications@github.com>
wrote:

> This should be fixed in 1.3.7, now on babel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Annotald/annotald/issues/81#issuecomment-148034096>.
>



-- 
C.E.A. Diertani
Ph.D., Linguistics
University of Pennsylvania

*****

Most beautiful things are common.

~ Michael Faraday, 1861

It is not madness, but sanity which is the arbitrary social category...

~ Christopher R. Badcock, 1980
